### PR TITLE
Add project keys management idea

### PR DESCRIPTION
**Pull request by danielgomezrico**
We can organize and know where the keys/quota do we have for each project.

### CODE REVIEW

**Comment by juancolarte** [comment]
We already use consul to alert on internal services.. it has a dashboard and a service of key/values ... we could use that to store and retrieve application keys....

**Comment by danielgomezrico** [comment]
@juancolarte yeah! for keys management sounds cool but for google services you need to have a google account with the associated services, I mean here console.developers.google.com.

+1 to check consul too

**Comment by edwaraco** [comment]
@caipivara could you do rebase please? thanks!

**Comment by danielgomezrico** [comment]
Rethinking about it and now looks like it's not a good idea, it will make us have a lot of accounts to handle per project.

**Pull request closed without merging**
