### PR TITLE
+ android dev flow 1.0

### PR DESCRIPTION
**Pull request by danielgomezrico**

### CODE REVIEW

**Comment by sarcilav** [comment]
@danielgomezrico can we get a bigger img? I was not able to read the text, sorry

**Comment by danielgomezrico** [comment]
@sarcilav maybe now?

**Comment by 0x5d** [comment]
I think the `feature/<v>` branches shouldn't be grouped under `feature`. A new version may consist of many features, so implementing a new feature doesn't necessarily mean a new version will be released. How about just calling the version branches `vMAJOR.MINOR.PATCH`? Please tell me if I got something wrong @danielgomezrico

**Comment by danielgomezrico** [comment]
@castillobg you are right, release branches should be `release/*`.

**Pull request merged**
