### PR TITLE
+ naming convention for backend.

### PR DESCRIPTION
**Pull request by danielgomezrico**
The idea is to avoid having some endpoints with different param name conventions.

### CODE REVIEW

**Comment by sarcilav** [comment]
why not `-`?

**Comment by danielgomezrico** [comment]
I just wanted to propose one... `-` works too.

**Comment by Busta117** [comment]
`_` or `-` works, but we have to decide, pickup is a mess, but to be clear for the next development

**Comment by sarcilav** [comment]
I prefer dashes over underscores

**Comment by danielgomezrico** [comment]
+1 dashes

**Comment by orendon** [comment]
<3 dashes

**Pull request merged**
