### PR TITLE
Add sample README proposal

### PR DESCRIPTION
**Pull request by orendon**
As discussed on today `Kaizen` session "some" repos are lacking a good README documentation, this PR aims to be a starting point of discussion/proposal so we have a seamless documentation across all projects

### CODE REVIEW

**Comment by danielgomezrico** [comment]
+1

**Review by lordaniel — APPROVED** [review]
@orendon Amazing Job :smile:

**Comment by orendon** [comment]
can we merge this? or do you guys have any extra suggestions?

**Comment by danielgomezrico** [comment]
Are there any projects without a readme?

**Comment by orendon** [comment]
@caipivara yes, we have a some projects without a README

**Comment by danielgomezrico** [comment]
then +1 to close it when we have them with it, otherwise I believe that it will become forgoten

**Comment by orendon** [comment]
I've updated all backend projects with this convention, any other suggestion or can we merge this baby?

**Review by danielgomezrico — APPROVED** [review]
No problem with two different objects 👍

**Review by Busta117 — APPROVED** [review]
👍

**Review by Juanadelacuesta — APPROVED** [review]

**Pull request merged**
